[tool.poetry]
name = "shuup-product-variations"
version = "1.0.13"
description = "Shuup Product Variations"
authors = ["Shuup <devs@shuup.com>"]


[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
